services:
  kafka:
    image: apache/kafka:latest
    platform: linux/amd64
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KAFKA_NODE_ID is required for KRaft mode
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  namesrv:
    image: apache/rocketmq:latest
    platform: linux/amd64
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:latest
    platform: linux/amd64
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAMESRV_ADDR=namesrv:9876
    entrypoint:
      - sh
      - -c
      - |
        echo "brokerIP1 = 127.0.0.1" > ../conf/broker.conf
        echo "autoCreateTopicEnable = true" >> ../conf/broker.conf
        sh mqbroker -c ../conf/broker.conf
    depends_on:
      - namesrv
